# Paths
models_path: "/dss/dsstbyfs02/pn52ru/pn52ru-dss-0000/common/datasets/clutter6d/3d_models"
cc_textures_path: "/dss/dsstbyfs02/pn52ru/pn52ru-dss-0000/common/datasets/clutter6d/cctextures" 
output_dir: "/dss/dsstbyfs02/pn52ru/pn52ru-dss-0000/di97jur/clutter6d/data" 

# Scene generation parameters
num_scenes: 3  
min_object_classes_per_scene: 10
max_object_classes_per_scene: 20
min_images_per_scene: 20 #25
max_images_per_scene: 30 #35

# Render resolution
resolution: [640, 480] # Devidable by 14 for ViT backbone compatibility

# Instance parameters
max_instances_per_object: 10  # Maximum number of instances per object (hard cap)
max_total_instances: 40      # Maximum total instances across all objects in a scene

# Poisson distribution parameters for instance selection
poisson_lambda: 3.5 # Lambda parameter (rate), lower values favor fewer instances
poisson_shift: -2

# Object size parameters
min_object_size: 0.15
max_object_size: 0.3

# Object position sampling parameters
position_sampling:
  min_radius: 0.2  # Minimum radius from center for object placement
  max_radius: 0.4  # Maximum radius from center for object placement
  min_height: 0.3  # Minimum height for object placement
  max_height: 0.5  # Maximum height for object placement

# Camera parameters
camera:
  radius_min: 0.5    # Minimum distance from center for camera placement
  radius_max: 2.0    # Maximum distance from center for camera placement
  elevation_min: 5   # Minimum elevation angle in degrees
  elevation_max: 89  # Maximum elevation angle in degrees