# Default configuration for Clutter6D dataset generation

# 3D Model Settings
models:
  data_dir: "/dss/dsstbyfs02/pn52ru/pn52ru-dss-0000/common/datasets/clutter6d/3d_models/"
  collections: ["GSO", "Objaverse", "OmniObject3D"]
  max_models: 10000
  supported_formats: [".glb", ".obj", ".ply"]
  
# Scene Generation Settings
scene:
  object_count_range: [5, 20]          # Min and max objects per scene
  allow_multiple_instances: true        # Allow multiple instances of same class
  multiple_instance_prob: 0.3          # Probability of having multiple instances
  max_instances_per_class: 3           # Maximum instances of same object class
  min_visibility_threshold: 0.2        # Minimum visibility ratio (20%)
  scene_bounds: [-2.0, 2.0, -2.0, 2.0, 0.0, 3.0]  # [x_min, x_max, y_min, y_max, z_min, z_max]
  
# Physics Simulation Settings
physics:
  gravity: [0, 0, -9.81]
  simulation_steps: 100
  max_simulation_time: 10.0            # Maximum simulation time in seconds
  collision_margin: 0.01               # Collision detection margin
  enable_physics: true
  drop_height_range: [0.5, 2.0]        # Height range for dropping objects
  
# Camera Settings
camera:
  image_size: [640, 480]
  fov_range: [40, 80]                  # Field of view range in degrees
  distance_range: [1.0, 4.0]          # Distance from scene center
  elevation_range: [-30, 60]          # Elevation angle range in degrees
  azimuth_range: [0, 360]             # Azimuth angle range in degrees
  look_at_jitter: 0.1                 # Random jitter for look-at point
  
# Lighting Settings
lighting:
  hdri_dir: "hdris/"
  use_hdri: true
  hdri_strength_range: [0.5, 2.0]
  additional_lights: true
  num_additional_lights_range: [1, 3]
  light_energy_range: [10, 100]
  
# Rendering Settings
rendering:
  engine: "CYCLES"                     # CYCLES or EEVEE
  samples: 256                         # Number of samples for CYCLES
  denoising: true
  motion_blur: false
  depth_of_field: false
  
# Material and Texture Settings
materials:
  enable_material_randomization: true
  pbr_material_prob: 0.7              # Probability of using PBR materials
  metallic_range: [0.0, 1.0]
  roughness_range: [0.1, 1.0]
  
# Output Settings
output:
  save_blend_files: false
  annotation_format: "coco"            # coco, yolo, or custom
  depth_format: "png"                  # png or exr
  depth_scale: 1000.0                  # Scale factor for depth values
  save_intermediate_steps: false
  
# Quality Control Settings
quality_control:
  min_objects_visible: 3               # Minimum number of visible objects
  max_occlusion_ratio: 0.8            # Maximum allowed occlusion ratio
  min_scene_coverage: 0.3              # Minimum scene coverage by objects
  balance_classes: true                # Enable class balancing
  
# Dataset Generation Settings
dataset:
  num_scenes: 1000
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  random_seed: 42
  
# Logging Settings
logging:
  log_level: "INFO"
  save_generation_log: true
  save_scene_metadata: true
  log_performance_metrics: true
